server:
  port: 8877
spring:
  cloud:
    config:
      server:
        git:
          password:
          searchPaths: respo
          uri: https://github.com/forezp/SpringcloudConfig/
          username:
      label: master
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

